In [1]:
import pandas as pd
import statsmodels.api as sm

value_y_list = [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4]
value_x1_list = [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10]
value_x2_list = [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68]
value_x3_list = [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8]
value_x4_list = [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]
data={'y': value_y_list, 'x1': value_x1_list, 'x2': value_x2_list, 'x3': value_x3_list, 'x4': value_x4_list}
df = pd.DataFrame(data)
df

,y,x1,x2,x3,x4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26


In [3]:
import numpy as np
import statsmodels.api as sm

# Select the 'x' columns from the df DataFrame
X_df = df[['x1', 'x2', 'x3', 'x4']]

# Add a constant column of ones
X_with_const_df = sm.add_constant(X_df)

# Convert the resulting DataFrame to a NumPy array
X_array = X_with_const_df.to_numpy()

# Display the NumPy array
print(X_array)

[[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]
 [ 1. 11. 55.  9. 22.]
 [ 1.  3. 71. 17.  6.]
 [ 1.  1. 31. 22. 44.]
 [ 1.  2. 54. 18. 22.]
 [ 1. 21. 47.  4. 26.]
 [ 1.  1. 40. 23. 34.]
 [ 1. 11. 66.  9. 12.]
 [ 1. 10. 68.  8. 12.]]


In [4]:
# Calculate the transpose of X_array
X_array_transpose = X_array.T

# Display the transposed array
print(X_array_transpose)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 7.  1. 11. 11.  7. 11.  3.  1.  2. 21.  1. 11. 10.]
 [26. 29. 56. 31. 52. 55. 71. 31. 54. 47. 40. 66. 68.]
 [ 6. 15.  8.  8.  6.  9. 17. 22. 18.  4. 23.  9.  8.]
 [60. 52. 20. 47. 33. 22.  6. 44. 22. 26. 34. 12. 12.]]


In [5]:
import numpy as np

# Extract the 'y' column as a NumPy array
y_vector = df['y'].to_numpy()

# Display the y vector
print(y_vector)

[ 78.5  74.3 104.3  87.6  95.9 109.2 102.7  72.5  93.1 115.9  83.8 113.3
 109.4]


In [9]:
import numpy as np

# Perform matrix multiplication of X_array_transpose by X_array
X_transpose_X = np.dot(X_array_transpose, X_array)

# Display the resulting matrix
print(X_transpose_X)

[[1.3000e+01 9.7000e+01 6.2600e+02 1.5300e+02 3.9000e+02]
 [9.7000e+01 1.1390e+03 4.9220e+03 7.6900e+02 2.6200e+03]
 [6.2600e+02 4.9220e+03 3.3050e+04 7.2010e+03 1.5739e+04]
 [1.5300e+02 7.6900e+02 7.2010e+03 2.2930e+03 4.6280e+03]
 [3.9000e+02 2.6200e+03 1.5739e+04 4.6280e+03 1.5062e+04]]


In [10]:
import numpy as np

# Calculate the inverse of X_transpose_X
X_transpose_X_inverse = np.linalg.inv(X_transpose_X)

# Perform the multiplication: (X^T * X)^-1 * X^T
intermediate_result = np.dot(X_transpose_X_inverse, X_array_transpose)

# Perform the final multiplication: ((X^T * X)^-1 * X^T) * y
beta_coefficients = np.dot(intermediate_result, y_vector)

# Display the regression coefficients
print("Regression Coefficients (Beta Hats):")
print(beta_coefficients)

Regression Coefficients (Beta Hats):
[62.4053693   1.55110265  0.51016758  0.1019094  -0.14406103]
